---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
- name: Upgrade all apt packages
  apt: upgrade=dist

- name: Install dependencies
  apt:
   name: "{{ packages }}"
   state: present
   update_cache: yes
   vars:
     packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg-agent
- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
- name: Install Docker
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    vars:
      packages:
      - docker.io

- name: create a docker network
  docker_network:
    name: gitea

- name: postgres container
  docker_container:
    name: postgres
    image: postgres:9.6
    state: started
    env:
      POSTGRES_DB: 'gitea'
      POSTGRES_USER: 'gitea'
      POSTGRES_PASSWORD: 'Admin@123'
    ports:
    - 5432:5432
    volumes:
    - /etc/postgres:/var/lib/postgresql/data
    networks:
    - name: gitea

- name: gitea container
  docker_container:
    name: gitea
    image: gitea/gitea:1.8.3
    ports:
    - 3000:3000
    volumes:
    - /home/ansibleadm/gitea:/data
    networks:
    - name: gitea

- name: Check if container is running
  shell: docker ps

